# Mirrored from https://gist.github.com/electronut/8a4c297213620958ebef
# Makefile for programming the ATtiny85
# modified the one generated by CrossPack

DEVICE      = attiny85
CLOCK      = 1000000 # Default clock divisor is 8 https://shallowsky.com/blog/hardware/attiny85-c.html
PROGRAMMER = -c usbtiny 
OBJECTS    = main.o
# for ATTiny85
# see http://www.engbedded.com/fusecalc/
FUSES       = -U lfuse:w:0x62:m -U hfuse:w:0xdf:m -U efuse:w:0xff:m 

# Tune the lines below only if you know what you are doing:
AVRDUDE = avrdude $(PROGRAMMER) -p $(DEVICE)
# Enable debugging so we can use an UNO as our debugger!
CXX = avr-g++ -Wall -g -Og -DF_CPU=$(CLOCK) -mmcu=$(DEVICE)
# symbolic targets:
all:	main.hex

.c.o:
	$(CXX) -c $< -o $@

.S.o:
	$(CXX) -x assembler-with-cpp -c $< -o $@

.c.s:
	$(CXX) -S $< -o $@

flash:	all
	$(AVRDUDE) -U flash:w:main.hex:i

fuse:
	$(AVRDUDE) $(FUSES)

# Xcode uses the Makefile targets "", "clean" and "install"
install: flash fuse

# if you use a bootloader, change the command below appropriately:
load: all
	bootloadHID main.hex

clean:
	rm -f main.hex main.elf $(OBJECTS)

# file targets:
main.elf: $(OBJECTS)
	$(CXX) -o main.elf $(OBJECTS)

main.hex: main.elf
	rm -f main.hex
	avr-objcopy -j .text -j .data -O ihex main.elf main.hex
	avr-size --format=avr --mcu=$(DEVICE) main.elf
# If you have an EEPROM section, you must also create a hex file for the
# EEPROM and add it to the "flash" target.

# Targets for code debugging and analysis:
disasm:	main.elf
	avr-objdump -d main.elf 

cpp:
	$(CXX) -E main.cpp